### ISSUE TITLE
'check_mode is not a legal parameter'

### ISSUE THREAD

**Issue by xvilo** [geerlingguy/ansible-role-redis#32]
When using current master ` 155a98cd` I get followig error:

```
web: Running ansible-playbook...
 [WARNING]: It is unnecessary to use '{{' in loops, leave variables in loop
expressions bare.

 [WARNING]: It is unnecessary to use '{{' in conditionals, leave variables in
loop expressions bare.

ERROR: check_mode is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

What am I doing wrong?

**Comment by geerlingguy** [comment]
Repurposing this ticket; I need to perform a few updates to this role to get it to play perfectly with Ansible 2.4+ and stop throwing warnings/notices :)

**Comment by geerlingguy** [comment]
@xvilo for your particular issue—are you sure you're posting in the correct Ansible role repository? There is no `check_mode` in this role currently, and there is no commit with a hash matching `155a98cd` anywhere that I can find.

Also, for the error you're seeing, usually the fix is to upgrade your Ansible version. Ansible 2.2 introduced `check_mode`; see http://docs.ansible.com/ansible/2.4/playbooks_checkmode.html (it replaced `always_run`. I'm guessing you're using Ansible 2.1 or earlier (which is unsupported by most projects and almost all my roles now).
